[build]
target = "./json_targets/x86_64-ableos.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]


[target.'cfg(target_arch = "x86_64")']
# --quite suppresses warning messages from the bootimage crate
runner = "bootimage runner --quiet"
