[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
[target.'cfg(target_arch = "x86_64")']
# --quite suppresses warning messages from the bootimage crate
runner = "bootimage runner --quiet"
