[build]
target = "./json_targets/x86_64-ableos.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]


[target.'cfg(target_arch = "x86_64")']
# --quiet suppresses warning messages from the bootimage crate
runner = "bootimage runner --quiet"
[target.riscv64gc-unknown-none-elf]
rustflags = "-C link-arg=-T../ableos/src/arch/riscv/virt.lds"
